# Generated by Django 5.2.5 on 2025-09-16 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluido'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('requerente', models.ForeignKey(limit_choices_to={'role': 'requerente'}, on_delete=django.db.models.deletion.CASCADE, related_name='chamados_requeridos', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(limit_choices_to={'role': 'responsavel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsaveis', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
