# Generated by Django 5.2.6 on 2025-09-17 14:04

import django.db.models.deletion
import django.utils.timezone
import gestao.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_chamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chamado',
            name='solucao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chamado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='responsavel',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'responsavel'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamados_responsaveis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_andamento', 'Em andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=20),
        ),
        migrations.CreateModel(
            name='ChamadoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=gestao.models.chamado_upload_path)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('chamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='gestao.chamado')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
